[package]
name = "client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Program client"

[dependencies]
palmtop-telemetry = { path = "../../crates/telemetry" }

tracing = "0.1.0"
serde_json = "1.0.94"
serde = { version = "1.0", default-features = false }
clap = { version = "4", features = ["derive"] }
dirs = "5.0.1"
tokio = { version = "1.28.0", features = ["full"] }
async-trait = "0.1.73"
eyre = "0.6.8"
tempfile = { version = "3.3.0" }
backon = "0.4"
hex = "0.4"
pretty_assertions = "1.3.0"

[target.'cfg(not(windows))'.dependencies]
jemallocator = { version = "0.5.0", optional = true }
jemalloc-ctl = { version = "0.5.0", optional = true }

[features]
default = ["jemalloc"]
jemalloc = ["dep:jemallocator", "dep:jemalloc-ctl"]
jemalloc-prof = ["jemalloc", "jemallocator?/profiling"]
min-error-logs = ["tracing/release_max_level_error"]
min-warn-logs = ["tracing/release_max_level_warn"]
min-info-logs = ["tracing/release_max_level_info"]
min-debug-logs = ["tracing/release_max_level_debug"]
min-trace-logs = ["tracing/release_max_level_trace"]

[build-dependencies]
vergen = { version = "8.0.0", features = ["build", "cargo", "git", "gitcl"] }
